#Indicamos el lenguaje usado.
Language: minimal
#Instalamos Docker.
services:
  - docker
#Con esto nos descargamos nuestro contenedor
before_install:
  - docker pull josemip98/organizeudiet
#Por Ãºltimo ejecutamos dicho contenedor para lanzar los tests.
script: docker run -t -v `pwd`:/test josemip98/organizeudiet
